version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
  db:
    image: postgres:9.2
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
